# Generated by Django 6.1.1 on 2026-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
