# Generated by Django 6.1.1 on 2026-09-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
