# Generated by Django 6.1.1 on 2026-09-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_profile_description_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(choices=[('software_eng', 'Software Engineering'), ('ai_ml', 'Artificial Intelligence & Machine Learning'), ('data_science', 'Data Science & Big Data'), ('cybersecurity', 'Cybersecurity & Network Defense'), ('web_dev', 'Web Development'), ('devops', 'DevOps & Cloud Computing'), ('hardware_embedded', 'Hardware & Embedded Systems'), ('game_dev', 'Game Development'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate / Ph.D.'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('details', models.TextField(null=True)),
                ('year', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
